// Mocks generated by Mockito 5.0.16 from annotations
// in flutterbloc/test/features/number_trivia/domain/usecases/get_concrete_number_trivia_test.dart.
// Do not manually edit this file.

import 'package:flutterbloc/features/number_trivia/domain/usecases/get_concrete_number_trivia.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'get_concrete_number_trivia_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GetConcreteNumberTrivia].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcreteNumberTrivia extends _i1.Mock
    implements _i2.GetConcreteNumberTrivia {
  MockGetConcreteNumberTrivia() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MockNumberTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockNumberTriviaRepository extends _i1.Mock
    implements _i3.MockNumberTriviaRepository {
  MockMockNumberTriviaRepository() {
    _i1.throwOnMissingStub(this);
  }
}
